/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import Logo from "../navbar/Logo";
import Link from "next/link";
import { useRouter } from "next/router";
import SocialIcons from "./SocialIcons";
import { CallIcon, ClockIcon, MailIcon } from "../shared/Icons";

const Footer: React.FC = () => {
  const router = useRouter();
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const companyLinks = [
    "About Us",
    "Our Services",
    "Industries",
    "Products",
    "Resources",
    "Contact Us",
  ];
  const usefulLinks = ["Careers", "Blog", "Team", "Features"];
  const productLinks = [
    "Co-Pilot",
    "Advance Analytics Tool",
    "Feedback Foresight",
    "Product 4",
  ];
  return (
    <footer className="flex flex-col w-full  bg-accent">
      <div className="container">
        <div className="grid md:grid-cols-2 lg:grid-cols-10 gap-7 md:gap-5 justify-between py-6 md:py-12">
          <div className="flex flex-col ml-5 max-md:ml-0 max-md:w-full col-span-3">
            <div className="flex flex-col items-start w-full">
              <div>
                <Link href="/" passHref>
                  <a>
                    <img src="/PropVIVO.png" className="max-w-48" />
                  </a>
                </Link>
                <div className="flex gap-x-8 text-sm mt-5">
                  <div className="relative after:absolute after:w-2 after:h-2 after:rounded-full after:bg-white/80 after:top-1/2 after:-translate-y-1/2 after:ml-3 text-lightGreen">
                    Innovation
                  </div>
                  <div className="relative after:absolute after:w-2 after:h-2 after:rounded-full after:bg-white/80 after:top-1/2 after:-translate-y-1/2 after:ml-3 text-pvOrange">
                    Transparency
                  </div>
                  <div className="relative text-accent1">Reliability</div>
                </div>
              </div>
              <div className="mt-5 md:mt-10">
                <SocialIcons />
              </div>
            </div>
          </div>
          <div className="flex flex-col max-md:w-full col-span-2">
            <div className="flex flex-col grow items-start">
              <div className="text-2xl font-medium text-white font-outfit">
                Menu
              </div>
              <div
                className="flex shrink-0 mt-2 h-0.5 bg-lightGreen rounded w-5"
                style={{ height: "2px" }}
              />
              <ul
                className={`mt-6 space-y-2 transition-all duration-500 block mxl:top-20 left-0 right-0 p-0 footerMenu`}
              >
                <li className="cursor-pointer relative">
                  <Link href="/" passHref>
                    <a
                      className={
                        router.pathname === "/about"
                          ? "active text-lightGreen"
                          : "transition-all duration-300"
                      }
                    >
                      Home
                    </a>
                  </Link>
                </li>
                <li className="cursor-pointer relative">
                  <Link href="/about" passHref>
                    <a
                      className={
                        router.pathname === "/about"
                          ? "active text-lightGreen"
                          : "transition-all duration-300"
                      }
                    >
                      About Us
                    </a>
                  </Link>
                </li>
                <li className="cursor-pointer relative">
                  <Link href="/ResaleCertificate" passHref>
                    <a
                      className={
                        router.pathname === "/ResaleCertificate"
                          ? "active text-lightGreen"
                          : "transition-all duration-300"
                      }
                    >
                      Documents
                    </a>
                  </Link>
                </li>
                <li className="cursor-pointer relative">
                  <Link href="/blog" passHref>
                    <a
                      className={
                        router.pathname === "/blog"
                          ? "active text-lightGreen"
                          : "transition-all duration-300"
                      }
                    >
                      Blog
                    </a>
                  </Link>
                </li>
                <li className="cursor-pointer relative">
                  <Link href="/contact" passHref>
                    <a
                      className={
                        router.pathname === "/contact" ? "!text-maroon" : ""
                      }
                    >
                      Contact Us
                    </a>
                  </Link>
                </li>
              </ul>
            </div>
          </div>
          <div className="flex flex-col max-md:w-full col-span-3">
            <div className="flex flex-col grow items-start">
              <div className="text-2xl font-medium text-white font-outfit">
                Services
              </div>
              <div
                className="flex shrink-0 mt-2 h-0.5 bg-lightGreen rounded w-5"
                style={{ height: "2px" }}
              />
              <ul
                className={`mt-6 space-y-2 transition-all duration-500 block mxl:top-20 left-0 right-0 p-0 footerMenu`}
              >
                <li className="cursor-pointer relative">
                  <Link href="/services" passHref>
                    <a
                      className={
                        router.pathname === "/services"
                          ? "active text-lightGreen"
                          : "transition-all duration-300"
                      }
                    >
                      Full-Service Management
                    </a>
                  </Link>
                </li>
                <li className="cursor-pointer relative">
                  <Link href="/services#tab2" passHref>
                    <a
                      className={
                        router.pathname === "/services#tab2"
                          ? "active text-lightGreen"
                          : "transition-all duration-300"
                      }
                    >
                      Financial Management
                    </a>
                  </Link>
                </li>
                <li className="cursor-pointer relative">
                  <Link href="/services#tab3" passHref>
                    <a
                      className={
                        router.pathname === "/services#tab3"
                          ? "active text-lightGreen"
                          : "transition-all duration-300"
                      }
                    >
                      Software Solution 
                    </a>
                  </Link>
                </li>
                <li className="cursor-pointer relative">
                  <Link href="/services#tab4" passHref>
                    <a
                      className={
                        router.pathname === "/services#tab4"
                          ? "active text-lightGreen"
                          : "transition-all duration-300"
                      }
                    >
                      Compliance & Legal
                    </a>
                  </Link>
                </li>
                <li className="cursor-pointer relative">
                  <Link href="/services#tab5" passHref>
                    <a
                      className={
                        router.pathname === "/services#tab5"
                          ? "active text-lightGreen"
                          : "transition-all duration-300"
                      }
                    >
                      Vendor Coordination
                    </a>
                  </Link>
                </li>
              </ul>
            </div>
          </div>
          <div className="flex flex-col max-md:w-full col-span-2">
            <div className="flex flex-col grow items-start">
              <div className="text-2xl font-medium text-white font-outfit">
                Contact
              </div>
              <div
                className="flex shrink-0 mt-2 h-0.5 bg-lightGreen rounded w-5"
                style={{ height: "2px" }}
              />
              <ul
                className={`mt-6 space-y-3 transition-all duration-500 block mxl:top-20 left-0 right-0 p-0`}
              >
                <li className="relative flex gap-2">
                  <CallIcon /> <a href="tel:+1 (888) 392-3515"><span className="flex-1 text-17 text-white/70">+1 (888) 392-3515</span></a>
                </li>
                <li className="relative flex gap-2">
                  <MailIcon />{" "}
                  <a href="mailto:services@propvivo.com"><span className="flex-1 text-17 text-white/70">services@propvivo.com</span></a>
                </li>
                <li className="relative flex gap-2">
                  <ClockIcon />{" "}
                  <span className="flex-1 text-17 text-white/70">
                    2018 156th Ave NE, Bellevue WA 98007
                  </span>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div className="border-t border-white/20 py-4 md:py-5 gap-4 text-center">
          <p className="text-white/70 mb-0">
            Copyright &#169; propVIVO 2025 | All Rights Reserved
          </p>
          {/* <p className="text-white/70 mb-0">
            Best viewed with IE 11, Firefox 76+, Safari 11+, Chrome 83+, Edge
            81+.
          </p> */}
        </div>
      </div>
    </footer>
  );
};

export default Footer;
