trigger:
  - main

pool:
  vmImage: 'windows-latest'

jobs:
  - job: Build
    strategy:
      matrix:
        dev:
          env: 'dev'
        QA:
          env: 'QA'
        stage:
          env: 'stage'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'

      - script: |
          npm install --force
        displayName: 'Install dependencies'
      
      - script: |
          npm run lint
        displayName: 'npm lint'

      - script: |
          npm run build:$(env)
        displayName: 'Building the $(env) Environment'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(env)/$(Build.BuildId)-$(env).zip'
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(env)'
          ArtifactName: 'drop-$(env)'
          publishLocation: 'Container'
