export const requestSubType = {
  Add: "Add",
  Update: "Update",
  Delete: "Delete",
  List: "List",
  Export: "Export",
  Upload: "Upload",
  Download: "Download",
  Cancel: "Cancel",
  Complete: "Complete",
  Reopen: "Reopen",
  Phone: "Phone",
  Reply: "Reply",
  abcc:"abcc",
  userProfileUpdate:"userProfileUpdate"
};

export const requestType = {
  ARCRequest: "ARCRequest",
  BoardTask: "BoardTask",
  GlobalMaster: "GlobalMaster",
  SocialEvents: "Events",
  SocialPoll: "Polls",
  AnnouncementCategory: "AnnouncementCategory",
  AnnouncementTemplate: "AnnouncementTemplate",
  ServiceRequest: "ServiceRequest",
  Currency: "Currency",
  Media: "Media",
  FiscalCalendar: "FiscalCalendar",
  FiscalYear: "FiscalYear",
  COA: "COA",
  LegalEntityFiscalCalendar: "LegalEntityFiscalCalendar",
  Country: "Country",
  State: "State",
  City: "City",
  ZipCode: "ZipCode",
  VendorRequest: "VendorRequest",
  LegalEntity: "LegalEntity",
  LegalEntityType: "LegalEntityType",
  BankAccount: "BankAccount",
  BankFundTransferConfiguration: "BankFundTransferConfiguration",
  CheckList: "CheckList",
  LegalEntityFeatureRolePermission: "LegalEntityFeatureRolePermission",
  MyRequest: "MyRequest",
  CaseNotes: "CaseNotes",
  Election: "Elections",
  SocialAnnouncement: "Announcement",
  Committee: "Committee",
  CommitteeType: "CommitteeType",
  UserProfile: "UserProfile",
  APVendor: "APVendor",
  BoardMembers: "BoardMembers",
  MemberDirectory: "MemberDirectory",
  Meeting: "Meeting",
  Meetings: "Meeting",
  CaseTopic: "CaseTopic",
  User: "User",
  CaseCategory: "CaseCategory",
  LegalEntityAddressMapping: "LegalEntityAddressMapping",
  DocumentLibrary: "Documents",
  Feedback: "Feedback",
  MarketPlace: "Market Place",
  EnumConfiguration:"EnumConfiguration",
  Violation: "Violation",
  AssociationByUser: "AssociationByUser",
  CCNRType: "CCNRType",
  abcc:"abcc",
  userRequest:"userRequest",
  GeographicalData:"GeographicalData",
  MyProfile:"MyProfile",
  UserRole:"UserRole",
  UnitOccupantDocuments:"UnitOccupantDocuments",
  UnitDocument:"UnitDocument",
  CondoQuestionnaire:"CondoQuestionnaire",
  OneTimePayment:"OneTimePayment",
};

export const containerName = {
  APVendor: "apvendor",
  SocialPoll: "polls",
  SocialEvent: "socialevent",
  election: "election",
  SocialAnnouncement: "socialannouncement",
  BoardMember: "boardmember",
  meeting: "meeting",
  Committee: "committee",
  feedback: "feedback",
  MarketPlace: "marketplace",
  Violation: "violation",
  CaseNotes: "casenotes"
};
